version: 2.0
jobs:
  build:
    docker:
      - image: ekidd/rust-musl-builder:1.18.0
    steps:
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/hello
